import { useEffect, useMemo, useRef, useState } from "react";
import { Mic, MicOff, PhoneOff, Volume2, VolumeX, X } from "lucide-react";
import { lianxinApi } from "../services/lianxinApi";

type VoiceEvent = { id: number; type: string; state?: string; content?: string; error?: string };
const API = "http://127.0.0.1:8766/api/video-call/assets/";
const states: Record<string, string> = { CONNECTING: "莲心等待中…", LISTENING: "可以直接说话", PROCESSING: "莲心思考中…", SPEAKING: "莲心正在说话", USER_SPEAKING: "莲心倾听中…", ERROR: "语音识别暂不可用", STOPPED: "通话已结束", ENDED: "通话已结束" };
const asset = (name: string) => `${API}${encodeURIComponent(name)}`;

export function VideoCallPanel({ onClose, userAvatar }: { onClose: () => void; userAvatar?: string }) {
  const [active, setActive] = useState(false); const [mic, setMic] = useState(true); const [speaker, setSpeaker] = useState(true); const [subtitles, setSubtitles] = useState(true); const [state, setState] = useState("CONNECTING"); const [sttReady, setSttReady] = useState(false); const [events, setEvents] = useState<VoiceEvent[]>([]); const [error, setError] = useState(""); const [seconds, setSeconds] = useState(0); const [wave, setWave] = useState(false); const [videoName, setVideoName] = useState("startup.mp4"); const mediaRef = useRef<HTMLVideoElement>(null);
  const latest = useMemo(() => [...events].reverse().find((item) => item.type === "voice.reply" || item.type === "voice.transcript"), [events]);
  const videoSource = videoName;
  useEffect(() => { let cursor = 0; let disposed = false; const poll = async () => { try { const result = await lianxinApi.voiceEvents(cursor); if (disposed) return; if (result.items.length) { cursor = result.latest; setEvents((current) => [...current, ...result.items].slice(-30)); result.items.forEach((item) => { if (item.type === "voice.state" && item.state) setState(item.state); if (item.type === "voice.transcript") setWave(true); if (item.type === "voice.stt") { setSttReady(item.state === "ready"); if (item.state === "ready") void lianxinApi.stopCallSound().catch(() => undefined); } if (item.type === "voice.tts" && item.state) { setState(item.state === "speaking" ? "SPEAKING" : "LISTENING"); setWave(item.state === "speaking"); } if (item.type === "voice.error") { setState("ERROR"); setError(item.error || "语音通话发生错误"); } }); } } catch (exc) { if (!disposed) setError(String(exc)); } }; const start = async () => { try { await lianxinApi.startCallSound(); const result = await lianxinApi.startVoice(); if (!disposed) { setActive(true); setState(result.state || "LISTENING"); } } catch (exc) { if (!disposed) { setState("ERROR"); setError(String(exc)); await lianxinApi.stopCallSound().catch(() => undefined); } } }; void lianxinApi.voiceStatus().then((result) => { if (!disposed && result.active) { setActive(true); setState(result.state || "LISTENING"); } else if (!disposed) void start(); }).catch(() => void start()); const timer = window.setInterval(() => void poll(), 350); void poll(); return () => { disposed = true; window.clearInterval(timer); void lianxinApi.stopCallSound().catch(() => undefined); }; }, []);
  useEffect(() => { const timer = window.setInterval(() => { setSeconds((value) => value + (active ? 1 : 0)); if (state !== "SPEAKING" && state !== "USER_SPEAKING") setWave(false); }, 1000); return () => window.clearInterval(timer); }, [active, state]);
  useEffect(() => { const video = mediaRef.current; if (!video) return; video.load(); void video.play().catch(() => undefined); }, [videoSource]);
  useEffect(() => () => { void lianxinApi.stopVoice().catch(() => undefined); }, []);
  const toggle = () => { setError(""); if (active) void lianxinApi.stopVoice().then((result) => { setActive(false); setState(result.state); }).catch((exc) => setError(String(exc))); else void lianxinApi.startCallSound().then(() => lianxinApi.startVoice()).then((result) => { setActive(true); setState(result.state); }).catch((exc) => setError(String(exc))); };
  const toggleMic = () => { const next = !mic; setMic(next); void lianxinApi.setVoiceMic(!next).catch((exc) => { setMic(!next); setError(String(exc)); }); };
  const toggleSpeaker = () => { const next = !speaker; setSpeaker(next); if (!next) void lianxinApi.stopSpeaking().catch(() => undefined); };
  const hangup = () => { void lianxinApi.stopVoice().finally(() => { setActive(false); setState("ENDED"); onClose(); }); };
  const time = `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;
  return <div className="video-call-overlay"><section className="video-call-legacy"><div className="video-call-media"><div className="video-call-blur" /><video ref={mediaRef} className="video-call-portrait" poster={asset("lianxin-poster.jpg")} src={asset(videoSource)} autoPlay muted playsInline onError={() => setError("莲心视频资源加载失败，请检查后端资源接口")} onEnded={() => setVideoName(`waiting-${1 + Math.floor(Math.random() * 3)}.mp4`)} onLoadedData={() => mediaRef.current?.play().catch(() => undefined)} /><div className="video-call-top"><strong>莲心 AI 视频聊天</strong><span>语音通话&nbsp;&nbsp;{time}</span><em>{states[state] || state}</em></div><div className="video-call-user"><div className="video-call-user-image" style={userAvatar ? { backgroundImage: `url(${userAvatar})` } : { backgroundImage: `url(${asset("user-avatar.jpg")})` }} /><span>{wave ? (state === "SPEAKING" ? "🔊 莲心 · 正在说话" : "🎙 用户 · 正在说话") : "🎙 用户 · 仅语音"}</span></div>{subtitles && latest?.content && <div className={`video-call-subtitle ${latest.type === "voice.transcript" ? "is-user" : ""}`}>{latest.type === "voice.transcript" ? `用户：${latest.content}` : `莲心：${latest.content}`}</div>}{state === "CONNECTING" && <div className="video-call-connecting"><div className="video-call-wave" /><span>莲心正在连接 FunASR，请稍等…</span></div>}<div className={`video-call-volume-wave ${wave ? "is-active" : ""}`}>{[.34,.58,.86,.58,.34].map((height, index) => <i key={index} style={{ height: `${wave ? height * (45 + ((seconds * 3 + index * 11) % 34)) : height * 8}px` }} />)}</div>{error && <p className="video-call-error">{error}</p>}</div><div className="video-call-legacy-controls"><button onClick={toggleMic} className={!mic ? "is-off" : ""}>{mic ? <Mic size={19} /> : <MicOff size={19} />}<span>{mic ? "麦克风" : "已静音"}</span></button><button onClick={toggleSpeaker} className={!speaker ? "" : "is-off"}>{speaker ? <Volume2 size={19} /> : <VolumeX size={19} />}<span>{speaker ? "扬声器" : "已静音"}</span></button><button onClick={() => setSubtitles((value) => !value)} className={!subtitles ? "is-off" : ""}><span>{subtitles ? "字幕" : "字幕关"}</span></button><button className="call-hangup" onClick={active ? hangup : toggle}>{active ? <PhoneOff size={21} /> : <Mic size={21} />}<span>{active ? "挂断" : (sttReady ? "开始通话" : "连接中")}</span></button><button onClick={hangup}><X size={19} /><span>关闭</span></button></div></section></div>;
}
